#!/usr/bin/env python3
"""CUDA-Q QAOA solver for mapping-only QUBO.

Accepts QUBO bundles generated by qubo_builder.py.
Implements QUBO to Ising conversion, QAOA ansatz (p=1, p=2),
COBYLA optimization, and bitstring sampling/decoding.
"""

from __future__ import annotations

import time
from typing import Any

import cudaq


def upper_triangle_terms(Q: list[list[float]]) -> tuple[list[tuple[int, float]], list[tuple[int, int, float]], float]:
    """Extract linear and quadratic coefficients mapping QUBO (x in {0,1}) to Ising (z in {-1,+1})."""
    linear: list[tuple[int, float]] = []
    quadratic: list[tuple[int, int, float]] = []
    offset = 0.0
    n = len(Q)
    for i in range(n):
        for j in range(i, n):
            coeff = float(Q[i][j])
            if coeff == 0:
                continue
            if i == j:
                offset += coeff / 2.0
                linear.append((i, -coeff / 2.0))
            else:
                offset += coeff / 4.0
                linear.append((i, -coeff / 4.0))
                linear.append((j, -coeff / 4.0))
                quadratic.append((i, j, coeff / 4.0))
                
    # Group linear terms by qubit index to simplify Hamiltonian construction
    linear_grouped: dict[int, float] = {}
    for idx, c in linear:
        linear_grouped[idx] = linear_grouped.get(idx, 0.0) + c
    linear_final = [(idx, c) for idx, c in linear_grouped.items() if c != 0.0]
    
    return linear_final, quadratic, offset


def build_spin_operator(Q: list[list[float]]) -> tuple[cudaq.spin.SpinOperator, float]:
    """Build the SpinOperator Hamiltonian for observe()."""
    linear, quadratic, offset = upper_triangle_terms(Q)
    terms = []
    
    for idx, coeff in linear:
        terms.append(coeff * cudaq.spin.z(idx))
    for i, j, coeff in quadratic:
        terms.append(coeff * cudaq.spin.z(i) * cudaq.spin.z(j))
        
    if not terms:
        # Safely return a zero Hamiltonian if Q matrix is empty
        hamiltonian = 0.0 * cudaq.spin.z(0)
    else:
        hamiltonian = terms[0]
        for term in terms[1:]:
            hamiltonian += term
            
    return hamiltonian, offset


def build_qaoa_kernel(
    n_qubits: int,
    p: int,
    linear: list[tuple[int, float]],
    quadratic: list[tuple[int, int, float]],
):
    """Build the QAOA ansatz kernel using rz and cx decomposition."""
    kernel, params = cudaq.make_kernel(list)
    qubits = kernel.qalloc(n_qubits)
    
    # Prepare initial superposition state
    for i in range(n_qubits):
        kernel.h(qubits[i])

    param_index = 0
    for _layer in range(p):
        gamma = params[param_index]
        beta = params[param_index + 1]
        param_index += 2
        
        # Cost Hamiltonian evolution:
        # 1. Linear terms: exp(-i * gamma * c * Z_i) = rz(2 * gamma * c, q_i)
        for idx, coeff in linear:
            kernel.rz(2.0 * gamma * coeff, qubits[idx])
            
        # 2. Quadratic terms: exp(-i * gamma * c * Z_i * Z_j) = cx(q_i, q_j), rz(2 * gamma * c, q_j), cx(q_i, q_j)
        for i, j, coeff in quadratic:
            kernel.cx(qubits[i], qubits[j])
            kernel.rz(2.0 * gamma * coeff, qubits[j])
            kernel.cx(qubits[i], qubits[j])
        
        # Mixer Hamiltonian evolution: exp(-i * beta * sum(X_i))
        for i in range(n_qubits):
            kernel.rx(2.0 * beta, qubits[i])
            
    return kernel, params


def bitstring_from_samples(samples: Any) -> str:
    try:
        return str(samples.most_probable())
    except Exception:
        return ""


def decode_assignment(bits: str, variables: dict[str, dict[str, Any]]) -> dict[str, str]:
    assignment: dict[str, str] = {}
    for name, info in variables.items():
        idx = int(info["index"])
        if idx < len(bits) and bits[idx] == "1":
            assignment[str(info["job_id"])] = str(info["node_id"])
    return assignment


def run_solver(
    qubo_payload: dict[str, Any],
    p: int = 1,
    optimizer_steps: int = 100,
    seed: int = 42,
    shots: int = 1024,
    jobs: list[dict[str, Any]] | None = None,
    nodes: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    """Solve the mapping QUBO using CUDA-Q QAOA."""
    Q = qubo_payload["Q"]
    variables = qubo_payload["variables"]
    n_qubits = len(Q)
    
    linear, quadratic, offset = upper_triangle_terms(Q)
    hamiltonian, _ = build_spin_operator(Q)
    kernel, params = build_qaoa_kernel(n_qubits, p, linear, quadratic)

    optimizer = cudaq.optimizers.COBYLA()
    optimizer.max_iterations = optimizer_steps
    optimizer.initial_parameters = [0.1] * (2 * p)

    cudaq.reset_target()
    cudaq.set_random_seed(seed)

    started = time.perf_counter()
    
    def objective(theta: list[float]) -> float:
        if shots > 0:
            result = cudaq.observe(kernel, hamiltonian, theta, shots_count=shots)
        else:
            result = cudaq.observe(kernel, hamiltonian, theta)
        return float(result.expectation())

    energy, opt_params = optimizer.optimize(2 * p, objective)
    sampling_shots = shots if shots > 0 else 1000
    samples = cudaq.sample(kernel, opt_params, shots_count=sampling_shots)
    elapsed = time.perf_counter() - started

    # Feasibility filter: find the most probable feasible assignment if jobs and nodes are provided
    best_bitstring = None
    if jobs is not None and nodes is not None:
        from assignment_validator import validate_assignment
        sorted_samples = sorted(samples.items(), key=lambda item: -item[1])
        for bits, count in sorted_samples:
            assignment = decode_assignment(bits, variables)
            if validate_assignment(assignment, jobs, nodes)["valid"]:
                best_bitstring = bits
                break

    if best_bitstring is None:
        best_bitstring = bitstring_from_samples(samples)
        
    if not best_bitstring:
        best_bitstring = "0" * n_qubits
        
    assignment = decode_assignment(best_bitstring, variables)

    return {
        "assignment": assignment,
        "best_bitstring": best_bitstring,
        "expected_value": energy + offset,
        "optimal_parameters": opt_params,
        "runtime_seconds": elapsed,
    }
